# Generated by Django 3.1.6 on 2021-06-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plants',
            old_name='plants_Main_Img',
            new_name='Img',
        ),
        migrations.RemoveField(
            model_name='plants',
            name='name',
        ),
    ]
